### ISSUE TITLE
[AUR] build cursors for plasma5-themes-sweet-full-git

### ISSUE THREAD

**Issue by Gigas002** [Gigas002/awesome-sweet#1]
I'm thinking about pushing the change for AUR package, that would require users to rebuild cursors theme on package update with `inkscape`. Related lines:

https://github.com/Gigas002/awesome-sweet/blob/79b4347062c9154a9f5aa359ac6abb982ea62298/aur/plasma5-themes-sweet-full-git/PKGBUILD#L81

The below patch file is also related, until https://github.com/EliverLara/Sweet/pull/265 isn't reviewed/merged:

https://github.com/Gigas002/awesome-sweet/blob/master/aur/plasma5-themes-sweet-full-git/cursors.patch

@dr460nf1r3 do you agree with the following changes? I don't think it'll introduce breaking behavior for chaotic aur users or garuda users, but will increase compile times for a bit

The reason for this change is the introduction of a `sweet-cursors-hyprcursor-git` package, which relies on building cursors. I though it'd be good to have same flow here and there.

**Comment by dr460nf1r3** [comment]
Sounds good to me. Can't really see how it would be a breaking change either. And I'm not too worried about compilation times either 😁

Short note for the README: the theme *does* work with VSCodium. Can confirm from first-hand experience :)

**Comment by Gigas002** [comment]
Nice, thanks for checking this out! Will push update to AUR soon.
